session_name: da_base
windows:
  - window_name: test no 3
    panes:
      - shell_command:
        - python3 main.py -g 7 -m base -s amazon -t dslr -l 3e-3 -e 100 -i 3
        - python3 main.py -g 7 -m base -s dslr -t amazon -l 3e-3 -e 100 -i 3

  - window_name: test no 6
    panes:
      - shell_command:
          - python3 main.py -g 6 -m base -s amazon -t dslr -l 1e-2 -b 64 -e 100 -i 3
          - python3 main.py -g 6 -m base -s dslr -t amazon -l 1e-2 -b 64 -e 100 -i 3

  - window_name: tensorboard
    panes:
      - tensorboard --logdir=log/tensor_board
