session_name: da_base
windows:
  - window_name: amazon
    panes:
      - shell_command:
        - python3 main.py -g 2 -r 1996 -m base -s amazon -t dslr
#        - python3 main.py -g 6 -r 1997 -m base -s amazon -t dslr
#        - python3 main.py -g 6 -r 1998 -m base -s amazon -t dslr
#        - python3 main.py -g 6 -r 1996 -m base -s amazon -t webcam
#        - python3 main.py -g 6 -r 1997 -m base -s amazon -t webcam
#        - python3 main.py -g 6 -r 1998 -m base -s amazon -t webcam

  - window_name: dslr
    panes:
      - shell_command:
          - python3 main.py -g 3 -r 1997 -m base -s amazon -t dslr
#          - python3 main.py -g 7 -r 1996 -m base -s dslr -t amazon
#          - python3 main.py -g 7 -r 1997 -m base -s dslr -t amazon
#          - python3 main.py -g 7 -r 1998 -m base -s dslr -t amazon
#          - python3 main.py -g 7 -r 1996 -m base -s dslr -t webcam
#          - python3 main.py -g 7 -r 1997 -m base -s dslr -t webcam
#          - python3 main.py -g 7 -r 1998 -m base -s dslr -t webcam

  - window_name: webcam
    panes:
      - shell_command:
          - python3 main.py -g 4 -r 1998 -m base -s amazon -t dslr
#          - python3 main.py -g 4 -r 1996 -m base -s webcam -t amazon
#          - python3 main.py -g 4 -r 1997 -m base -s webcam -t amazon
#          - python3 main.py -g 4 -r 1998 -m base -s webcam -t amazon
#          - python3 main.py -g 4 -r 1996 -m base -s webcam -t dslr
#          - python3 main.py -g 4 -r 1997 -m base -s webcam -t dslr
#          - python3 main.py -g 4 -r 1998 -m base -s webcam -t dslr

  - window_name: tensorboard
    panes:
      - tensorboard --logdir=log/tensor_board
