session_name: da_base
windows:
  - window_name: amazon
    panes:
      - shell_command:
        - python3 main.py -g 5 -m base -s amazon -t dslr -l 1e-2 -e 100 -i 3
        - python3 main.py -g 5 -m base -s amazon -t webcam -l 1e-2 -e 100 -i 3

  - window_name: dslr
    panes:
      - shell_command:
        - python3 main.py -g 5 -m base -s dslr -t amazon -l 1e-2 -e 100 -i 3
        - python3 main.py -g 5 -m base -s dslr -t webcam -l 1e-2 -e 100 -i 3

  - window_name: webcam
    panes:
      - shell_command:
        - python3 main.py -g 5 -m base -s webcam -t amazon -l 1e-2 -e 100 -i 3
        - python3 main.py -g 5 -m base -s webcam -t dslr -l 1e-2 -e 100 -i 3

  - window_name: tensorboard
    panes:
      - tensorboard --logdir=log/tensor_board
